/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateFileDto
 */
export interface CreateFileDto {

    /**
     * @type {string}
     * @memberof CreateFileDto
     */
    folderId: string;

    /**
     * @type {string}
     * @memberof CreateFileDto
     */
    name: string;

    /**
     * @type {number}
     * @memberof CreateFileDto
     */
    size: number;

    /**
     * @type {string}
     * @memberof CreateFileDto
     */
    mimeType: string;
}
