/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Folder
 */
export interface Folder {

    /**
     * @type {string}
     * @memberof Folder
     */
    id: string;

    /**
     * @type {string}
     * @memberof Folder
     */
    name: string;

    /**
     * @type {Array<string>}
     * @memberof Folder
     */
    subfolders: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof Folder
     */
    files: Array<string>;
}
