/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Folder } from "./folder";
/**
 *
 *
 * @export
 * @interface FolderInfoDTO
 */
export interface FolderInfoDTO {
  /**
   * @type {string}
   * @memberof FolderInfoDTO
   */
  id: string;

  /**
   * @type {string}
   * @memberof FolderInfoDTO
   */
  name: string;

  /**
   * @type {Array<Folder>}
   * @memberof FolderInfoDTO
   */
  subfolders: Array<Folder>;

  /**
   * @type {Array<Array>}
   * @memberof FolderInfoDTO
   */
  files: Array<Array>;

  /**
   * @type {Folder}
   * @memberof FolderInfoDTO
   */
  sharingTree: Folder;
}
