/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InvitedUserData } from './invited-user-data';
 /**
 * 
 *
 * @export
 * @interface InvitedUser
 */
export interface InvitedUser {

    /**
     * @type {string}
     * @memberof InvitedUser
     */
    permission: InvitedUserPermissionEnum;

    /**
     * @type {InvitedUserData}
     * @memberof InvitedUser
     */
    user: InvitedUserData;
}

/**
 * @export
 * @enum {string}
 */
export enum InvitedUserPermissionEnum {
    Read = 'read',
    Write = 'write'
}

