/* tslint:disable */
/* eslint-disable */
/**
 * Your API
 * API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface InvitedUserData
 */
export interface InvitedUserData {
  /**
   * @type {string}
   * @memberof InvitedUserData
   */
  userId: string;

  /**
   * @type {string}
   * @memberof InvitedUserData
   */
  givenName: string;

  /**
   * @type {string}
   * @memberof InvitedUserData
   */
  name: string;

  /**
   * @type {any}
   * @memberof InvitedUserData
   */
  picture: any;
}
