version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: oneplacedb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306